valor = input('Digite algo: ')
print('O tipo primitivo desse número é ', type(valor))
print('only space ? ', valor.isspace())
print('Is it a number ? ', valor.isnumeric())
print('É alfabetico ? ', valor.isalpha())
print('É alfaumerico ? ', valor.isalnum())
print('Está em maiúscula ? ', valor.isupper())
print('Está em minúscula ? ', valor.islower())
print('Está captalizada ? ', valor.istitle())