num = int(input('Digite um número para ver sua tabuada: '))
print('-'*12)
print(f'{num}*{1:2} = {num+1}')
print(f'{num}*{2:2} = {num+2}')
print(f'{num}*{3:2} = {num+3}')
print(f'{num}*{4:2} = {num+4}')
print(f'{num}*{5:2} = {num+5}')
print(f'{num}*{6:2} = {num+6}')
print(f'{num}*{7:2} = {num+7}')
print(f'{num}*{8:2} = {num+8}')
print(f'{num}*{9:2} = {num+9}')
print(f'{num}*{10:2} = {num+10}')
print('-'*12)