frase = 'Curso em Video Python'
frase2 = '   testando Espaços   '
dividido = frase.split()
'''Exemplos'''
print(frase[3])
print(frase[3:13])
print(frase[:13])
print(frase[13:])
print(frase[1:15:2])
print(frase[1::3])
print(frase[::2])
print(len(frase))
print(frase.count('o'))
print(frase.find('deo'))
print(frase.replace('Python', 'Android'))
print(frase.upper())
print(frase.lower())
print(frase.capitalize())
print(frase.title())
print(frase2)
print(frase2.strip())
print(frase2.rstrip())
print(frase2.lstrip())
print(frase.split())
print(''.join(frase))
print(dividido[0])
